pipeline {
    agent {
        docker {
            image 'arm64v8/maven:3.6.2-slim'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}